# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: npm
    directories: ["/", "tasks/SpectralLintTaskV0"]
    schedule:
      interval: weekly
      day: thursday
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
    groups:
      github-actions:
        patterns:
          - "*"